# Generated by Django 6.0.3 on 2026-03-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('istemolchi', 'istemolchi'), ('ofitsiant', 'ofitsiant')], default='istemolchi')),
                ('phone_number', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('is_active', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
