# Generated by Django 6.0.3 on 2026-03-08 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message=" telefon raqami +9989 dan boshlanib 9 ta raqamdan iborat bo'lishi kerak!", regex='^\\+998\\d{9}$')]),
        ),
    ]
