# Generated by Django 6.0.3 on 2026-03-18 09:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_post_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Istemolchi', 'Istemolchi'), ('Ofitsiant', 'Ofitsiant')], default='istemolchi', max_length=20)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message=" telefon raqami +9989 dan boshlanib 9 ta raqamdan iborat bo'lishi kerak!", regex='^\\+998\\d{13}$')])),
                ('address', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
