# Generated by Django 6.0.3 on 2026-03-30 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message=" telefon raqami +998 dan boshlanib 9 ta raqamdan iborat bo'lishi kerak!", regex='^\\+998\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Istemolchi', 'Istemolchi'), ('Ofitsiant', 'Ofitsiant')], default='Istemolchi', max_length=20),
        ),
    ]
