# Generated by Django 6.0.3 on 2026-03-18 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofitsiant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stock',
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='image',
            field=models.ImageField(blank=True, default='taomlar/default.jpg', null=True, upload_to='taomlar/'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='preparation_time',
            field=models.PositiveIntegerField(help_text='Minutlarda'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
