# Generated by Django 6.0.3 on 2026-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofitsiant', '0002_remove_category_stock_alter_taomlar_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taomlar',
            name='preparation_time',
            field=models.IntegerField(default=10),
        ),
    ]
