# Generated by Django 6.0.3 on 2026-03-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofitsiant', '0003_alter_taomlar_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
