# Generated by Django 6.0.3 on 2026-03-30 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_note_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='+998 dan boshlanib 13 ta belgidan iborat bolishi kerak', regex='^\\+998\\d{9}$')]),
        ),
    ]
